### PR TITLE
Various rubik_scrambler enhancements

### PR DESCRIPTION
**Pull request by selliott512**
I've made various changes that I hope are helpful.  Some highlights:
- Increased the number of moves that are supported, including double layer moves.
- Added additional keys to bypass animation, scramble, hide non-cube parts of the display, etc.
- Reduced CPU usage.
- Undo key.
  Feel free to send me feedback.

### CODE REVIEW

**Comment by unrealsid** [comment]
@selliott512  Hi! Sorry, it took me a while to go through the modifications. Could you provide a list of mappings that exist between keys and the functions you included/updated? Also, thanks for improving the render function. It looks much neater now!

**Comment by selliott512** [comment]
@XanderWraik Unfortunately I haven't logged into github for a while, so I didn't see this.

I've made a bunch of additional modifications since the last pull request.  I'm thinking of releasing it as my own program with a different name.  The splash screen will credit you by saying "by Steven Ellliott based on rubik_scrambler by XanderWraik".  Let me know if you'd rather it have your real name.  I'll also release it under the MIT license, just like rubik_scrambler.  I figured we had different ideas about which direction it should go.  I hope that's ok.  When I publish it, most likely on github, I'll send you the URL.

As to your question: Most of the key bindings are in EventListeners.js:
    case "A": // (A)nimation toggle
    case "C": // (C)orner view toggle
    case "G": // Undo (like Ctrl-G in Emacs)
    case "H": // (H)ide toggle
    case "J": // (J)umble (S was taken)
    case "N": // (N)new cube
    case "O": // (O)rientation display toggle.
In addition to that I think I added rotating the entire cube "X Y and Z".  I made scrambling J for jumble since I wanted to use M, E and S for middle moves.

Thanks for writing this program.  It fills a niche for a keyboard based cube.  I've enjoyed working on it and playing with it.

**Comment by unrealsid** [comment]
@selliott512 Yes, I don't have any issues. Feel free to play around and release it as you see fit. 
Yes, I'd prefer having my real name on there. 
No, I'm quite comfortable with the changes you've made. However, I spotted one critical bug in the final release which is why I had reverted the changes. I'm outlining it here:
You ensured CPU cycles are not utilized when the cube is not interacted with, however, I noticed that this freezes the cube completely, thereby completely disabling mouse interactivity, which is not something you'd want while solving. If you can work that issue out, it'd be great, then you may not even need to release an updated version on your site. It could persist here only. But anyhow, it's entirely upto you.

**Comment by selliott512** [comment]
@XanderWraik That sounds great.  I see from your profile that your real name is Siddhante Nangla, so I'll use that without "XanderWraik" in the readme.  But if you'd rather I put both with something like "Siddhante Nangla aka XanderWraik" I'm happy to do that too.  I'm Steven Elliott, by the way.  If you'd rather reach me by email you can at selliott512@gmail.com.

I noticed that bug too.  I should have notified you.  I ended up fixing it in my version by running the animation loop while any mouse button is pressed, but still suspending animation when neither a mouse button nor key is pressed.  I'll share more info shortly.

**Comment by selliott512** [comment]
I've published my copy named QWERTYcube at http://selliott.org/puzzles/qwertycube.  I'm curious what you think of it.  As to the bug you mentioned - if you look in QWERTYcube you can see how that was fixed.  A variable is set when a mouse button is pressed:

``` javascript
function onMouseDown(event) {
    // The user may be adjusting the camera if a mouse button is done. When
    // in doubt animate.
    if (!infoDisplayed) {
        cameraAdjusting = true;
        animateCondReq(true);
    }
}
```

And that variable is checked in the animation logic:

``` javascript
function animateCondReq(needed) {
    animateNeeded = needed;

    // This method requests that doAnimate() be called next frame if need be.
    if (animateNeeded || moveCurrent || moveQueue.length || statusDisplayed
            || cameraAdjusting || timer) {
        window.requestAnimationFrame(doAnimate);
    }
}
```

**Comment by unrealsid** [comment]
@selliott512 Hi. Just had a look at it. Yeah, it's definitely good. I like the features you added. It's without a doubt an evolved version of 'rubik_scrambler'. It supports the full set of rotations that you'd come to expect from an actual cube app. I see that you refined the UI also quite a bit: The colours used are quite appealing. You got rid of the bug, which was important for a good user experience. What's left is to allow rotation of a face by dragging a layer: This may be harder to achieve, but should be well worth a try.

**Pull request merged**
